services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fifa_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  extract:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./data:/app/data
      - ~/.kaggle:/root/.kaggle
    environment:
      - PYTHONPATH=/app
    command: python -m services.extract.main

  transform:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    command: python -m services.transform.main
    depends_on:
      - extract

  load:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    command: python -m services.load.main
    depends_on:
      - transform
      - postgres

volumes:
  postgres_data: 